export const MAIN_SET_MESSAGE = 'MAIN_SET_MESSAGE';
export const MAIN_SET_FETCHING = 'MAIN_SET_FETCHING';
export const MAIN_SET_SCROLLING = 'MAIN_SET_SCROLLING';
export const MAIN_SET_OVERLAY = 'MAIN_SET_OVERLAY';
export const MAIN_SET_CREATE_STATE = 'MAIN_SET_CREATE_STATE';
export const MAIN_SET_EDIT_STATE = 'MAIN_SET_EDIT_STATE';
export const MAIN_SET_DELETE_STATE = 'MAIN_SET_DELETE_STATE';
export const IS_SIDEBAR_ACTIVE = 'IS_SIDEBAR_ACTIVE';
